# Generated by Django 4.0.4 on 2022-06-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0003_alter_orderplaced_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
